// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file GpsImuFusionData2.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "GpsImuFusionData2.h"

#include <ucdr/microcdr.h>
#include <string.h>

bool GpsImuFusionData2_serialize_topic(ucdrBuffer* writer, const GpsImuFusionData2* topic)
{
    (void) ucdr_serialize_int32_t(writer, topic->latitude);

    (void) ucdr_serialize_int32_t(writer, topic->longitude);

    (void) ucdr_serialize_int32_t(writer, topic->altitude);

    (void) ucdr_serialize_float(writer, topic->velocity_n);

    (void) ucdr_serialize_float(writer, topic->velocity_e);

    (void) ucdr_serialize_float(writer, topic->velocity_d);

    (void) ucdr_serialize_float(writer, topic->roll);

    (void) ucdr_serialize_float(writer, topic->pitch);

    (void) ucdr_serialize_float(writer, topic->yaw);

    return !writer->error;
}

bool GpsImuFusionData2_deserialize_topic(ucdrBuffer* reader, GpsImuFusionData2* topic)
{
    (void) ucdr_deserialize_int32_t(reader, &topic->latitude);

    (void) ucdr_deserialize_int32_t(reader, &topic->longitude);

    (void) ucdr_deserialize_int32_t(reader, &topic->altitude);

    (void) ucdr_deserialize_float(reader, &topic->velocity_n);

    (void) ucdr_deserialize_float(reader, &topic->velocity_e);

    (void) ucdr_deserialize_float(reader, &topic->velocity_d);

    (void) ucdr_deserialize_float(reader, &topic->roll);

    (void) ucdr_deserialize_float(reader, &topic->pitch);

    (void) ucdr_deserialize_float(reader, &topic->yaw);

    return !reader->error;
}

uint32_t GpsImuFusionData2_size_of_topic(__attribute__((unused))const GpsImuFusionData2* topic, uint32_t size)
{
    uint32_t previousSize = size;
    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
